### ISSUE TITLE
Dokku Postgres Import fails with pipe error

### ISSUE THREAD

**Issue by aswinmohanme** [dokku/dokku-postgres#194]
I had an already existing app on Heroku that I'm migrating to Dokku. The platform is really awesome and way easier than configuring your own server. 

I took a `heroku pg:backups download` dump file and imported the file into the server. But when I run `dokku postgres:import < latest.dump` it fails with the error `read unix @->/var/run/docker.sock: read: connection reset by peer`

The dump file is over 3mb and that might be the issue.

**Comment by vanastassiou** [comment]
@aswinmohanme about how long have you noticed the import taking? I don't have any ideas about solving your problem, but I'm wondering what "normal" behaviour looks like when doing `postgres:import`.

**Comment by aswinmohanme** [comment]
It displays the error at the execution time itself.

**Comment by jonian** [comment]
I'm having the same issue. I looks that the error occurs when you import a dump from **postgres 12** to **postgres 11**. I did not test the import from 11 to 12 with dokku, but locally it works without errors, so I guess it will work on dokku too.

> but I'm wondering what "normal" behaviour looks like when doing postgres:import

@vanastassiou when the import is successfull the command exits without any output.

**Comment by jnettome** [comment]
As written on README.md:
`Official postgres plugin for dokku. Currently defaults to installing postgres 11.6.`

So, what I did in order to run a newer version of postgres to be able to import my dump from heroku was:

- SSH on my instance running dokku
- Ran `docker pull postgres:12.5`
- Then, on my local machine, I've created a new postgres database running 12.5 via `ssh dokku@dokkuinstance postgres:create <DATABASE_NAME> -i postgres -I 12.5`

After those steps, I've tried to import it once again via `ssh dokku@dokkuinstance postgres:import <DATABASE_NAME> < latest.dump` successfully.

**Comment by josegonzalez** [comment]
Yeah postgres dumps (and the data directories?) don't seem to be compatible across major versions (not sure why tbh). Glad you've got it sorted.
